In [ ]:

import pandas as pd
import numpy as np
import collections
import re

In [ ]:
doc1 = 'Game of Thrones is an amazing tv series!'
doc2 = 'Game of Thrones is the best tv series!'
doc3 = 'Game of Thrones is so great'

In [ ]:
l_doc1 = re.sub(r"[^a-zA-Z0-9]", " ", doc1.lower()).split()
l_doc2 = re.sub(r"[^a-zA-Z0-9]", " ", doc2.lower()).split()
l_doc3 = re.sub(r"[^a-zA-Z0-9]", " ", doc3.lower()).split()

In [ ]:
l_doc1

['game', 'of', 'thrones', 'is', 'an', 'amazing', 'tv', 'series']

In [ ]:
wordset12 = np.union1d(l_doc1,l_doc2)
wordset =  np.union1d(wordset12,l_doc3)
print(wordset)

['amazing' 'an' 'best' 'game' 'great' 'is' 'of' 'series' 'so' 'the'
 'thrones' 'tv']

In [ ]:
def calculateBOW(wordset,l_doc):
  tf_diz = dict.fromkeys(wordset,0)
  for word in l_doc:
      tf_diz[word]=l_doc.count(word)
  return tf_diz

In [ ]:
bow1 = calculateBOW(wordset,l_doc1)
bow2 = calculateBOW(wordset,l_doc2)
bow3 = calculateBOW(wordset,l_doc3)
df_bow = pd.DataFrame([bow1,bow2,bow3])
df_bow.head()

   amazing  an  best  game  great  is  of  series  so  the  thrones  tv
0        1   1     0     1      0   1   1       1   0    0        1   1
1        0   0     1     1      0   1   1       1   0    1        1   1
2        0   0     0     1      1   1   1       0   1    0        1   0

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(stop_words='english',ngram_range=(2,3))
X = vectorizer.fit_transform([doc1,doc2,doc3])
df_bow_sklearn = pd.DataFrame(X.toarray(),columns=vectorizer.get_feature_names())
df_bow_sklearn.head()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,amazing tv,amazing tv series,best tv,best tv series,game thrones,game thrones amazing,game thrones best,game thrones great,thrones amazing,thrones amazing tv,thrones best,thrones best tv,thrones great,tv series
0,1,1,0,0,1,1,0,0,1,1,0,0,0,1
1,0,0,1,1,1,0,1,0,0,0,1,1,0,1
2,0,0,0,0,1,0,0,1,0,0,0,0,1,0

In [ ]:
vectorizer.vocabulary_

{'game thrones': 4,
 'thrones amazing': 8,
 'amazing tv': 0,
 'tv series': 13,
 'game thrones amazing': 5,
 'thrones amazing tv': 9,
 'amazing tv series': 1,
 'thrones best': 10,
 'best tv': 2,
 'game thrones best': 6,
 'thrones best tv': 11,
 'best tv series': 3,
 'thrones great': 12,
 'game thrones great': 7}